### ISSUE TITLE
PyData-Scattertext-Part-1.ipynb needs to be updated

### ISSUE THREAD

**Issue by bingoong** [JasonKessler/Scattertext-PyData#1]
Hi Jason, just want to say thanks for your codes! I have been looking for a long time for something like this and was almost going to give up. Now, I just hope it will work on my dataset. By the way, your corpus code does not work and needs to be updated. It should be:

corpus = st.CorpusFromPandas(convention_df, category_col='party', text_col='text',nlp=nlp).build()

instead of 

corpus = st.CorpusFromParsedDocuments(convention_df, category_col='party', parsed_col='parsed').build()

**Comment by JasonKessler** [comment]
Thanks, Bingoong.  I'll look into it.

**Comment by JasonKessler** [comment]
It works on my end.  You may want to make sure you update Scattertext to the most recent version. 

What error are you seeing?

**Comment by bingoong** [comment]
Sorry, it seems to work fine now for some reason, the 

corpus = st.CorpusFromParsedDocuments(convention_df, category_col='party', parsed_col='parsed').build()

Sorry for the false alarm!
